# Generated by Django 4.0.3 on 2022-03-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_user_admins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
