# Generated by Django 4.0.3 on 2022-03-19 15:04

from django.db import migrations, models
import pet_sitting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('petname', models.CharField(max_length=100)),
                ('petphoto', models.ImageField(blank=True, null=True, upload_to=pet_sitting.models.filepath)),
                ('petage', models.CharField(max_length=100)),
                ('petbreed', models.CharField(max_length=100)),
                ('petdescription', models.TextField()),
                ('petfood', models.CharField(max_length=100)),
                ('petsittingreason', models.TextField()),
            ],
        ),
    ]
