# Generated by Django 4.0.3 on 2022-03-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitting',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
