# Generated by Django 4.0.3 on 2022-03-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitting', '0003_alter_petsitting_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitting',
            name='petphoto',
        ),
    ]
