# Generated by Django 4.0.3 on 2022-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_sitting', '0004_remove_petsitting_petphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetSitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('petexp', models.TextField()),
            ],
        ),
    ]
