# Generated by Django 4.0.3 on 2022-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
