# Generated by Django 4.0.3 on 2022-03-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_confirm_password_user_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
