# Generated by Django 4.0.3 on 2022-03-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_address_remove_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmpassword',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='username',
        ),
    ]
