# Generated by Django 4.0.3 on 2022-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
