# Generated by Django 4.0.3 on 2022-03-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_alter_adoption_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoption',
            old_name='email',
            new_name='emailid',
        ),
    ]
