# Generated by Django 4.0.3 on 2022-03-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_rename_email_adoption_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='contact',
            field=models.CharField(max_length=200),
        ),
    ]
