# Generated by Django 4.0.3 on 2022-03-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0004_alter_adoption_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=150)),
                ('dogname', models.CharField(max_length=150)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Adoption',
        ),
    ]
