# Generated by Django 4.0.3 on 2022-03-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0003_alter_rescue_dogdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogdetails', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Rescue',
        ),
    ]
